name: family_app_flutter
description: "FamilyApp — единое семейное пространство: чаты, задачи, события, синхронизация с Firestore и шифрование PII."
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Firebase
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.4
  # firebase_auth: добавляйте только если реально используете
  # firebase_auth: ^5.1.4

  # Storage / шифрование
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # при необходимости PointyCastle или encrypt подключаются в security/*
  # pointycastle: ^3.7.4
  # encrypt: ^5.0.3

  # UI / утилиты
  intl: ^0.20.2
  table_calendar: ^3.2.0
  uuid: ^4.5.1
  path_provider: ^2.1.4
  file_picker: ^8.3.7

  # WebRTC (если реально используется в коде)
^flutter_webrtc: ^1.1.0

  # Для совместимости некоторых API (если встречаются js-interop)
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
