name: family_app_flutter
description: A cross-platform family management app built with Flutter.
version: 0.0.1

# Specify the Flutter SDK version and Dart SDK constraints.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  uuid: ^3.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  table_calendar: ^3.0.9
  intl: ^0.18.0
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  flutter_webrtc: ^1.1.0
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
