cat > pubspec.yaml <<'YAML'
name: family_app_flutter
description: "FamilyApp — единое семейное пространство: чаты, задачи, события, синхронизация с Firestore и шифрование PII."
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12

  # UI / утилиты
  intl: ^0.20.2
  table_calendar: ^3.2.0
  uuid: ^4.5.1
  path_provider: ^2.1.4
  file_picker: ^8.3.7

  # WebRTC
  flutter_webrtc: ^1.1.0
  # Для совместимости js-interop
  js: ^0.7.2

  # Хранилище
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
YAML
